### ISSUE TITLE
Duplicate Records,

### ISSUE THREAD

**Issue by smartfink** [IssabelFoundation/issabelPBX#16]
after a while of server working, We will have Duplicate on CDR and Recording.
We should unload extra odbc madule on module.conf but we should prevent this issue.

**Comment by asternic** [comment]
When asterisk 11 is installed, everything is ok. When selecting asterisk 13, then you might have both cdr_adaptative_odbc and cdr_mysql enabled. In this case the correct solution is not to use the cdr_mysql module by adding noload => cdr_mysql.so in /etc/asterisk/modules_custom.conf. Next version/release will do that.
