### ISSUE TITLE
Error in the blacklist module

### ISSUE THREAD

**Issue by agulliver** [IssabelFoundation/issabelPBX#23]
modules/blacklist/functions.inc.php: function blacklist_get_config($engine) 

>$id = "app-blacklist";
>$ext->addInclude('from-internal-additional', $id); // Add the include from from-internal
>$ext->add($id, $c, '', new ext_macro('user-callerid'));

the $c variable is not defined

As a result, the wrong context is generated

> [app-blacklist]
> include => app-blacklist-custom
> exten => ,1,Macro(user-callerid,)
> ;--== end of [app-blacklist] ==--;

log:
> ERROR[52942] pbx.c: You have to be kidding-- add exten '' to context app-blacklist? Figure out a name and call me back. Action ignored.

**Comment by asternic** [comment]
Thanks, fixed

https://github.com/IssabelFoundation/issabelPBX/commit/32fdd42ca56a543f92509532a80d84526ccfa607
