### ISSUE TITLE
Unembedded IssabelPbx User Control Panel

### ISSUE THREAD

**Issue by tbagwell** [IssabelFoundation/issabelPBX#3]
Bug: Unembedded IssabelPbx User Control Panel When you click on it. It will come back as /recordings not found on server

**Comment by ahmed89albttashi** [comment]
Can you describe issue in details

**Comment by tbagwell** [comment]
On the issabel side.     https://{ipadress}/admin
If you click on the User Control Panel there. It will try to take you to. https://{ipadress}/recordings
It will come up with a Not Found The requested url /recordings was not found on server
This happen in Iso from July and also in the iso of 1-2-18

**Comment by asternic** [comment]
ARI framework was removed for security reasons. There is a user control panel inside Issabel that is more feature rich. You can install the ARI Framework from the module admin in unembeded IssabelPBX if you want.

**Comment by markosjal** [comment]
Where is this 'feature rich' user control panel for  issabel? The main login? 

Also on my clean install last night /recordings shows the .htaccess file.

**Comment by asternic** [comment]
When logged into Issabel, you can associate an extension to any given user, then you have the My Extension menu option that will let you set/unset call forward, do not disturb, recordings, etc. Under reports you will access your CDR and Recordings, etc.

Best regards,

**Comment by asternic** [comment]
We are not going to continue supporting ari as user panel, in favor of "my extension" on issabel main login.

**Comment by abel408** [comment]
@asternic Anyway users can log into their voicemail from using their extension and pin like the old ARI module used to work? I have several hundred users and there is no way I'm going to create them all logins and tie them to their extension and manage those usernames and passwords. It makes a lot more sense to have them log in to a web interface with their extension and voicemail pin.
