### ISSUE TITLE
usage of databases

### ISSUE THREAD

**Issue by carepollo** [IssabelFoundation/issabelPBX#32]
I have two tables from different databases, one is call_center.calls and other is asteriskcdr.cdr, one has a huge record of data of the calls but the other as well. I want to know which of those stores the related data to the calls that the system execute by itself AND the calls manually made by humans.

Also: I have a problem with the date on the table audit, it says ODBC error 22007

**Comment by asternic** [comment]
Please post configuration or usage issues/doubts into the forum or telegram group. This place is for reporting code bugs.

**Comment by carepollo** [comment]
Understood.
