### ISSUE TITLE
Unembedded IssabelPbx User Control Panel

### ISSUE THREAD

**Issue by carlosribeiro** [IssabelFoundation/issabelPBX#45]
IssabelPbx 5 not option to open Unembedded IssabelPBX (FreePBX)
I need to get to the option "Asterisk Manager Users" on FreePBX to create user for monitoring by Zabbix

**Comment by asternic** [comment]
Not an issue, just a different way to use it comparing to Issabel 5.

Log out from Issabel and log directly to issabelPBX (https://your.server/admin), that is the way to get the unembeded version.
